Creation of an AUTHORS file.
ctsit/honeyguide pull request #3
Opened 2018-05-15 14:32 UTC by UF-Buck-GitHub

We need to make sure all projects have an AUTHORS file. I've created the standard file as used on other projects.

2018-05-15 15:58 UTC, senrabc requested changes
You need to update the text to reflect this is a honeyguide AUTHORS file

"Pigeon is used to copy redcap records into a new
+redcap project instance."

2018-05-21 19:01 UTC, PFWhite requested changes
looks great!

2018-05-21 19:01 UTC, PFWhite commented on AUTHORS
> +our authors and contributors. Pigeon is used to copy redcap records into a new
I think we should call it honeyguide

2018-05-21 19:01 UTC, UF-Buck-GitHub commented on AUTHORS
> +our authors and contributors. Pigeon is used to copy redcap records into a new
Looks good.

2018-05-21 19:09 UTC, PFWhite approved these changes

2018-05-21 19:09 UTC, merged